local test = require("santoku.test")
local err = require("santoku.error")
local assert = err.assert
local spans = require("santoku.spans")
local ivec = require("santoku.ivec")
local tbl = require("santoku.table")
local teq = tbl.equals

local function build ()
  local S = spans.create({ "s", "e", "ty" })
  S:push(0, 3, 1):push(4, 7, 2):doc()
  S:doc()
  S:push(2, 5, 1):doc()
  return S
end

test("spans: create/push/doc/accessors", function ()
  local S = build()
  assert(S:n() == 3)
  assert(S:n_docs() == 3)
  assert(teq(S:offsets():table(), { 0, 2, 2, 3 }))
  assert(teq(S:col("s"):table(), { 0, 4, 2 }))
  assert(teq(S:col("ty"):table(), { 1, 2, 1 }))
  assert(teq(S:names(), { "s", "e", "ty" }))
end)

test("spans: filter in place", function ()
  local S = build()
  assert(S:filter(ivec.create({ 1, 0, 1 })) == S)
  assert(S:n() == 2)
  assert(teq(S:offsets():table(), { 0, 1, 1, 2 }))
  assert(teq(S:col("s"):table(), { 0, 2 }))
end)

test("spans: docs gather", function ()
  local S = build()
  local O = S:docs(ivec.create({ 2, 0 }))
  assert(O:n_docs() == 2)
  assert(teq(O:offsets():table(), { 0, 1, 3 }))
  assert(teq(O:col("s"):table(), { 2, 0, 4 }))
end)

test("spans: append in place", function ()
  local A = build()
  local B = build()
  assert(A:append(B) == A)
  assert(A:n() == 6)
  assert(A:n_docs() == 6)
  assert(teq(A:offsets():table(), { 0, 2, 2, 3, 5, 5, 6 }))
  assert(teq(B:offsets():table(), { 0, 2, 2, 3 }))
end)

test("spans: per-doc stable sort", function ()
  local S = spans.create({ "s", "lab" })
  S:push(5, 10):push(1, 20):push(5, 30):doc()
  S:push(9, 40):push(2, 50):doc()
  S:sort("s")
  assert(teq(S:col("s"):table(), { 1, 5, 5, 2, 9 }))
  assert(teq(S:col("lab"):table(), { 20, 10, 30, 50, 40 }))
end)

test("spans: eq", function ()
  local A = build()
  local B = build()
  assert(A:eq(B))
  B:col("ty"):set(0, 9)
  assert(not A:eq(B))
end)

test("spans: surfaces with interning + lowercase", function ()
  local S = spans.create({ "s", "e" })
  S:push(0, 5):push(6, 11):doc()
  S:push(0, 5):doc()
  local texts = { "Hello World", "HELLO again" }
  local ids, surfs = S:surfaces(texts, true)
  assert(teq(ids:table(), { 0, 1, 0 }))
  assert(teq(surfs, { "hello", "world" }))
  local ids2, surfs2 = S:surfaces(texts)
  assert(teq(ids2:table(), { 0, 1, 2 }))
  assert(surfs2[1] == "Hello" and surfs2[3] == "HELLO")
end)

test("spans: persist/load roundtrip", function ()
  local tmp = ".spans_test.bin"
  local S = build()
  S:persist(tmp)
  local T = spans.load(tmp)
  os.remove(tmp)
  assert(S:eq(T))
  assert(teq(T:names(), { "s", "e", "ty" }))
end)
